import GlobalAppContext from "./context";

export type JsonObject = Record<string, any>;


export type ObjectWithLabelAndValue = {
    value: string
    label: string
}

export type ValidationBadgeProps = {
    condition: boolean
    warning?: boolean
}

export type Country = {
    id: number,
    name: string,
    phoneCode: string,
    emoji: string | null,
    iso3: string | null
}

// Generated by https://quicktype.io

export type ElementWithIdAndName = {
    id: number;
    name: string;
}


// Generated by https://quicktype.io

export type Notification = {
    id: number;
    userId: number;
    subject: string;
    message: string;
    type: number;
    date: Date;
    isRead: number;
    isActive: number;
}

export type WebsiteCurrency = {
    text: string;
    value: string;
    symbol: string;
    xof_value: number;
    decimal: number
}

export type AppSettings = {
    id: number,
    website_url: string | null
    sms_sender_name: string | null
    sms_api_access_token: string | null,
    admin_inner_bar_color: string,
    country: string,
    kilogram_shipping_price: number,
    standard_shipping_price: number,// Generated by https://quicktype.io
    flash_shipping_price: number,
    visit_price: number,
    currency: string,
    currencies: Record<string, WebsiteCurrency>
}

export type Config = {
    id?: string;
    status?: string;
    user_created?: string;
    date_created?: number;
    user_updated?: null | Date;
    date_updated?: null | Date;
    datasets: Dataset[];
}

export type Dataset = {
    id: string;
    status: string;
    sort: null | string;
    user_created: string;
    date_created: number;
    user_updated: string;
    date_updated: number;
    name: string;
    prediction_threshold: number;
    class_names: null | string[];
    model_eval_code: null | string;
    thumb: string | string;
    production_models: ProductionModel[];
}

export type ProductionModel = {
    id: number;
    datasets_id: string;
    models_id: string;
    model: Model;
}

export type Model = {
    id: string;
    status: string;
    sort: null | string;
    user_created: string;
    date_created: number;
    user_updated: string;
    date_updated: number;
    name: string;
    dataset_id: string;
    file: string;
    tfjs_file: string;
    session_id: string;
    config: string;
    tflite_file: null | string;
    tf_serving_file: null | string;
    version: number;
}

export type ComponentWithContextProp = {
    context: GlobalAppContext
}

export type ComponentWithIdAndContextProps = {
    id: any,
    context: GlobalAppContext
}

