// Generated by https://quicktype.io

export type Order = {
    id: string;
    status: string;
    sort: null| string;
    user_created: string;
    date_created: null;
    user_updated: null;
    date_updated: null;
    product_type: string;
    shipper_code: string;
    note: null;
    admin_note: null;
    customer_first_name: string;
    customer_last_name: string;
    customer_phone_number: string;
    customer_email: string;
    customer_country_id: number;
    customer_state_id: null;
    customer_city_id: number;
    customer_address: string;
    customer_address_2: null;
    starting_wished_service_date: null;
    selected_service_date: null;
    ending_wished_service_date: null;
    payment_type: string;
    shipping_type: string;
    payment_status: string;
    shipping_status: string;
    service_status: null;
    shipper_id: null;
    shipper_details: null;
    price: number;
    shipping_price: number;
    details: Detail[];
}

export type Detail = {
    id: number;
    status: string;
    sort: null;
    user_created: string;
    date_created: null;
    user_updated: null;
    date_updated: null;
    product_id: number;
    option: null;
    color: null;
    order_id: string;
    quantity: number;
}


