version: '3.3'
services:
  server:
    image: tensorflow/serving
    container_name: holypics
    ports:
      - '8501:8501'
    volumes:
      - './models:/models'
    command: --model_config_file=/models/models.config

  web:
    restart: always
    build: ./web/app
    ports:
      - 5501:5501
    volumes:
      - ./web/app:/code