version: '3.4'
services:
  tfserving:
    image: tensorflow/serving
    container_name: ${TF_SERVING_CONTAINER_NAME}
    ports:
      - ${TF_SERVING_PORT}:8501
    volumes:
      - './config/tf-serving/models:/models'
    env_file:
      - .env
    command: --model_config_file=/models/models.config
    restart: always
  api:
    container_name: ${API_CONTAINER_NAME}
    build:
      dockerfile: ./api/Dockerfile
      context: .
    restart: always
    ports:
      - '${API_PORT}:8055'
    volumes:
      - ./api/extensions:/app/extensions
      - api_uploads:/app/uploads
      # env_file:
      #   - ./environment/api.env
    environment:
      PORT: 8055
volumes:
  api_uploads:


