version: '3.4'
services:
  server:
    container_name: holypics_server
    build: 
      dockerfile: Dockerfile
      context: server
    restart: always
    env_file:
      - .env
      - ./config/environment/server.env
    ports:
      - ${HOLYPICS_SERVER_PORT}:81

  



