version: '3.3'
services:
  # server:
  #   image: tensorflow/serving
  #   container_name: holypics
  #   ports:
  #     - '8501:8501'
  #   volumes:
  #     - './models:/models'
  #   command: --model_config_file=/models/models.config

  # web:
  #   restart: always
  #   build: ./web/app
  #   ports:
  #     - 5501:5501
  #   volumes:
  #     - ./web/app:/code

  # pytest-python3.5:
  #   image: python:3.5
  #   container_name: myjupyterlab
  #   command: bash -c "apt-get install -y python3-opencv;python3 -m pip install --upgrade pip;pip3 install -r requirements-first.txt;jupyter-lab --ip='*' --port=8888 --allow-root --no-browser"
  #   volumes:
  #     - .:/app
  #   working_dir: /app
  #   ports:
  #     - 8888:8888
  #     - 6000:6000