version: '3.4'
services:

  website:
    container_name: ${WEBSITE_CONTAINER_NAME}
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${WEBSITE_PORT}:3000

  cache:
    container_name: ${CACHE_CONTAINER_NAME}
    image: redis:6
    env_file:
      - .env
    networks:
      - directus

  backoffice:
    container_name: ${BACKOFFICE_CONTAINER_NAME}
    restart: always
    # image: directus/directus:latest
    build:
      dockerfile: Dockerfile
      context: backoffice
    env_file:
      - .env
      - config/environment/backoffice.env
    ports:
      - ${BACKOFFICE_PORT}:8055
    depends_on:
      - db
      - cache
    volumes:
      - ./backoffice/extensions:/app/extensions
      - backoffice_migration:/app/migration
      - backoffice_uploads:/app/uploads
    networks:
      - directus

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:latest
    restart: always
    ports:
      - ${DB_PORT}:3306
    command:
      [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
      ]
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - directus

  tfserving:
    image: tensorflow/serving
    container_name: ${TF_SERVING_CONTAINER_NAME}
    ports:
      - ${TF_SERVING_PORT}:8501
    volumes:
      - './config/tf-serving/models:/models'
    env_file:
      - .env
    command: --model_config_file=/models/models.config

  filebrowser:
    image: hurlenko/filebrowser
    container_name: ${FILEBROWSER_CONTAINER_NAME}
    user: "${FILEBROWSER_UID}:${FILEBROWSER_GID}"
    ports:
      - ${FILEBROWSER_PORT}:8080
    volumes:
      - ./data:/data
      # - /CONFIG_DIR:/config
    env_file:
      - .env
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  jupyterlab:
    image: jupyter/base-notebook
    container_name: ${JUPYTERLAB_CONTAINER_NAME}
    ports:
      - ${JUPYTERLAB_PORT}:8888
    volumes:
      - ./data/datasets:/datasets
      - ./data/notebooks:/notebooks
    env_file:
      - .env

volumes:
  backoffice_uploads:
  backoffice_migration:
  db_data:


networks:
  directus:
