version: '3.4'
services:
  model_1:
    container_name: stable_diffusion
    restart: always
    image: r8.im/stability-ai/stable-diffusion@sha256:6359a0cab3ca6e4d3320c33d79096161208e9024d174b2311e5a21b6c7e1131c
    ports:
      - 5000:5000
