version: '3.4'
services:
  backoffice:
    container_name: ${BACKOFFICE_CONTAINER_NAME}
    restart: always
    build: 
      dockerfile: Dockerfile
      context: backoffice
    env_file:
      - .env
      - config/environment/backoffice.env
    ports:
      - ${BACKOFFICE_PORT}:8055
    volumes:
      - ./backoffice/extensions:/app/extensions
      - backoffice_uploads:/app/uploads
      - backoffice_migration:/app/migration

  # server:
  #   container_name: ${SERVER_CONTAINER_NAME}
  #   build: 
  #     dockerfile: Dockerfile
  #     context: server
  #   restart: always
  #   env_file:
  #     - .env
  #     - ./config/environment/server.env
  #   ports:
  #     - ${SERVER_PORT}:81
  #   volumes:
  #     - ./server/uploads:/usr/src/app/uploads
    
  # nginx:
  #   image: ${NGINX_CONTAINER_NAME}
  #   build: 
  #     dockerfile: Dockerfile-nginx
  #     context: server
  #   ports:
  #     - ${SERVER_NGINX_PORT}:80
  #   depends_on:
  #     - server

  # web:
  #   container_name: ${WEB_CONTAINER_NAME}
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: web
  #   ports:
  #     - ${WEBSITE_PORT}:3000

  # filebrowser:
  #   container_name: ${FILE_BROWSER_CONTAINER_NAME}
  #   image: hurlenko/filebrowser
  #   user: "${FILEBROWSER_UID}:${FILEBROWSER_GID}"
  #   ports:
  #     - ${FILEBROWSER_PORT}:8080
  #   volumes:
  #     - ./data:/data
  #     # - /CONFIG_DIR:/config
  #   environment:
  #     - FB_BASEURL=/filebrowser
  #   restart: always

  tfserver:
    image: tensorflow/serving
    container_name: ${TF_SERVING_CONTAINER_NAME}
    ports:
      - ${TF_SERVING_PORT}:8501
    volumes:
      - './models:/models'
    command: --model_config_file=/models/models.config
volumes:
  backoffice_uploads:
  backoffice_migration:


