version: '3.4'
services:
  website:
    container_name: ${WEBSITE_CONTAINER_NAME}
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${WEBSITE_PORT}:3000

  backoffice:
    container_name: ${BACKOFFICE_CONTAINER_NAME}
    restart: always
    build: 
      dockerfile: Dockerfile
      context: backoffice
    env_file:
      - .env
      - config/environment/backoffice.env
    ports:
      - ${BACKOFFICE_PORT}:8055
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - ./backoffice/extensions:/app/extensions
      - backoffice_migration:/app/migration
      - backoffice_uploads:/app/uploads

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:latest 
    restart: always
    ports:
      - ${DB_PORT}:3306 
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"


volumes:
  backoffice_uploads:
  backoffice_migration:
  db_data:


