version: '3.4'
services:
  server:
    container_name: holypics_server
    build: 
      dockerfile: Dockerfile
      context: server
    restart: always
    env_file:
      - .env
      - ./config/environment/server.env
    ports:
      - ${SERVER_PORT}:81
    volumes:
      -./uploads:/usr/src/app/uploads
    
  nginx:
    image: holypics_nginx
    build: 
      dockerfile: Dockerfile-nginx
      context: server
    ports:
      - ${SERVER_NGINX_PORT}:80
    depends_on:
      - server

  web:
    container_name: holypics_web
    restart: always
    build:
      dockerfile: Dockerfile
      context: web
    ports:
      - ${WEBSITE_PORT}:3000

  filebrowser:
    container_name: holypics_filebrowser
    image: hurlenko/filebrowser
    user: "${FILEBROWSER_UID}:${FILEBROWSER_GID}"
    ports:
      - ${FILEBROWSER_PORT}:8080
    volumes:
      - ./data:/data
      # - /CONFIG_DIR:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always

  



