version: '3.4'
services:

  website:
    container_name: ${WEBSITE_CONTAINER_NAME}
    restart: always
    build:
      context: app
      dockerfile: Dockerfile
    env_file:
      - .env
      # - config/environment/dashboard.env
    ports:
      - ${WEBSITE_PORT}:3000

  backoffice:
    container_name: ${BACKOFFICE_CONTAINER_NAME}
    restart: always
    build: 
      dockerfile: Dockerfile
      context: backoffice
    env_file:
      - .env
      - config/environment/backoffice.env
    ports:
      - ${BACKOFFICE_PORT}:8055
    volumes:
      - ./backoffice/extensions:/app/extensions
      - backoffice_uploads:/app/uploads
      - backoffice_migration:/app/migration

  # filebrowser:
  #   container_name: ${FILE_BROWSER_CONTAINER_NAME}
  #   image: hurlenko/filebrowser
  #   user: "${FILEBROWSER_UID}:${FILEBROWSER_GID}"
  #   ports:
  #     - ${FILEBROWSER_PORT}:8080
  #   volumes:
  #     - ./data:/data
  #     # - /CONFIG_DIR:/config
  #   environment:
  #     - FB_BASEURL=/filebrowser
  #   restart: always

  tfserver:
    image: tensorflow/serving
    container_name: ${TF_SERVING_CONTAINER_NAME}
    ports:
      - ${TF_SERVING_PORT}:8501
    volumes:
      - './models:/models'
    command: --model_config_file=/models/models.config

volumes:
  backoffice_uploads:
  backoffice_migration:


