export type CardDetail = {
    "id": number,
    "quantity": number,
    "option": string,
    "color": string
}

// Generated by https://quicktype.io

export type Order = {
    id: string;
    status: string;
    sort: null;
    user_created: string;
    date_created: string;
    user_updated: null;
    date_updated: null;
    shipper_code: string;
    note: null;
    product_type: string;
    customer_first_name: string;
    customer_last_name: string;
    customer_phone_number: string;
    customer_country_id: number;
    customer_state_id: null;
    customer_city_id: number;
    customer_address: string;
    customer_address_2: null;
    starting_wished_service_date: null;
    ending_wished_service_date: null;
    payment_type: string;
    shipping_type: string;
    payment_status: string;
    selected_service_date: null;
    admin_note: null;
    shipping_status: string;
    service_status: null;
    shipper_id: null;
    shipper_details: null;
    price: number;
    shipping_price: number;
    customer_email: string;
    number: string;
    canceled: number;
    coupon: null;
    details: Detail[];
}

export type Detail = {
    id: number;
    quantity: number;
    option: null;
    color: null;
}



