import GlobalAppContext from "./context";

export type JsonObject = Record<string, any>;

export type ObjectWithLabelAndValue = {
    value: string
    label: string
}

export type ValidationBadgeProps = {
    condition: boolean
    warning?: boolean
}

export type ComponentWithContextProp = {
    context: GlobalAppContext
}

export type ComponentWithIdAndContextProps = {
    id: any,
    context: GlobalAppContext
}

export type Country = {
    id: number,
    name: string,
    phoneCode: string,
    emoji: string | null,
    iso3: string | null
}

// Generated by https://quicktype.io

export type ElementWithIdAndName = {
    id: number;
    name: string;
}




// Generated by https://quicktype.io

export interface Notification {
    id: number;
    userId: number;
    subject: string;
    message: string;
    type: number;
    date: Date;
    isRead: number;
    isActive: number;
}

export type WebsiteCurrency = {
    text: string;
    value: string;
    symbol: string;
    xof_value: number;
    decimal: number
}

export type AppSettings = {
    id: number,
    website_url: string | null
    sms_sender_name: string | null
    sms_api_access_token: string | null,
    admin_inner_bar_color: string,
    country: string,
    kilogram_shipping_price: number,
    standard_shipping_price: number,
    flash_shipping_price: number,
    visit_price: number,
    currency: string,
    currencies: Record<string, WebsiteCurrency>
}