import GlobalAppContext from "./context";

export type JsonObject={
    [key: string]: any
}

export type ObjectWithLabelAndValue={
    value: string
    label: string
}

export type ValidationBadgeProps={
    condition: boolean
    warning?: boolean
}

export type ComponentWithContextProp = {
    context: GlobalAppContext
}

export type ComponentWithIdAndContextProps = {
    id: any,
    context: GlobalAppContext
}

export type Country = {
    id: number,
    name: string,
    phoneCode: string,
    emoji: string | null,
    iso3: string | null
}

    // Generated by https://quicktype.io

export type ElementWithIdAndName = {
    id:   number;
    name: string;
}




// Generated by https://quicktype.io

export interface Notification {
    id:       number;
    userId:   number;
    subject:  string;
    message:  string;
    type:     number;
    date:     Date;
    isRead:   number;
    isActive: number;
}
