// Generated by https://quicktype.io

export interface Product {
    id: number;
    status: string;
    user_created: string;
    date_created: string;
    user_updated: string;
    date_updated: string;
    name: string;
    description: null;
    thumb: string;
    city: null;
    category: number;
    sub_category: null;
    is_recommended: boolean;
    sub_sub_category: null;
    tags: null;
    commune: null;
    price: number;
    type: string;
    stock: number;
    colors: null;
    weight: null;
    state: null;
    price_before_promotion: null;
    position: Position;
    options: string[];
}

export interface Position {
    coordinates: number[];
    type: string;
}
